;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        backward-to-char
        clipboard-yank
        forward-to-char
        jg-delete-region-or-paredit-delete
        keyboard-quit
        kill-region
        paredit-delete-char
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        View-scroll-half-page-forward
        amx
        helm-confirm-and-exit-minibuffer
        jg-dispatch-mc
        markdown-outdent-or-delete
        mc/mark-next-lines
        suspend-frame
        ))
