;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        backward-to-char
        clipboard-yank
        jg-delete-region-or-paredit-delete
        keyboard-quit
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        amx
        markdown-outdent-or-delete
        mc/mark-next-lines
        suspend-frame
        ))
